apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
        tier: app
    spec:
#      imagePullSecrets:
#        - name: {{ .Values.serviceImage.pullSecret }}
      imagePullPolicy: {{ .Values.serviceImage.pullPolicy }}
      containers:
        - name: {{ .Values.app.name }}
          image: {{ .Values.serviceImage.name }}:{{ .Values.serviceImage.tag }}
          env:
            - name: INDEX_FILE
              value: "/demo/final_result.csv"
            - name:
            - name: REST_API_TOKEN
              value: "changeme"
          ports:
            - containerPort: {{ .Values.app.port }}
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "0.5"
      restartPolicy: Always
status: {}